name: Check GitHub Secrets

on:
  workflow_dispatch:
  push:
    branches: [main, staging, develop]

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Vérification des secrets GitHub Actions requis pour Vercel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          pnpm exec ts-node scripts/check-github-secrets.ts "$GITHUB_TOKEN" "$REPO_OWNER" "$REPO_NAME"
