name: E2E Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Install dependencies (root)
        run: pnpm install --frozen-lockfile
      - name: Run E2E tests
        run: pnpm --filter kaya-nexus run test:e2e
