name: Lighthouse CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install -g @lhci/cli
      - run: pnpm install
      - run: pnpm build
      - name: Start server
        run: pnpm start &
        env:
          NODE_ENV: production
      - name: Run Lighthouse CI
        run: lhci autorun --collect.url=http://localhost:3000
