# Commit technique pour forcer la réindexation CI/CD Windsurf et GitHub Actions (2)
#
name: Sentry Monitoring

on:
  push:
    branches:
      - main
      - develop

# Sentry monitoring workflow désactivé temporairement pour CI/CD stable
# Tout le bloc jobs est commenté pour éviter toute erreur YAML ou CI/CD.
# jobs:
#   sentry-release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Create Sentry release
#         uses: getsentry/action-release@v1
#         env:
#           SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
#           SENTRY_ORG: bigkunta
#           SENTRY_PROJECT: ton-projet
#         with:
#           environment: production
